function BlindDataForDistributionNoGKs = importfile(workbookFile, sheetName, dataLines)
%IMPORTFILE Import data from a spreadsheet
%  BLINDDATAFORDISTRIBUTIONNOGKS = IMPORTFILE(FILE) reads data from the
%  first worksheet in the Microsoft Excel spreadsheet file named FILE.
%  Returns the data as a table.
%
%  BLINDDATAFORDISTRIBUTIONNOGKS = IMPORTFILE(FILE, SHEET) reads from
%  the specified worksheet.
%
%  BLINDDATAFORDISTRIBUTIONNOGKS = IMPORTFILE(FILE, SHEET, DATALINES)
%  reads from the specified worksheet for the specified row interval(s).
%  Specify DATALINES as a positive scalar integer or a N-by-2 array of
%  positive scalar integers for dis-contiguous row intervals.
%
%  Example:
%  BlindDataForDistributionNoGKs = importfile("C:\Users\Darian\Documents\MATLAB\Atlanta\Blind Data For Distribution No GKs.xlsx", "Blind Data For Distribution(2)", [2, 8987]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 29-May-2021 10:47:41

%% Input handling

% If no sheet is specified, read first sheet
if nargin == 1 || isempty(sheetName)
    sheetName = 1;
end

% If row start and end points are not specified, define defaults
if nargin <= 2
    dataLines = [2, 8987];
end

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 69);

% Specify sheet and range
opts.Sheet = sheetName;
opts.DataRange = "A" + dataLines(1, 1) + ":BQ" + dataLines(1, 2);

% Specify column names and types
opts.VariableNames = ["player", "team", "Base", "Guaranteed", "Min", "Age", "AgeGroup", "Position", "PosCat", "Touches", "TchsA3", "TchsM3", "TchsD3", "TchsA2", "TchsD2", "TchsL3", "TchsC3", "TchsR3", "PsAtt", "PsCmp", "PsAttA3", "PsCmpA3", "PsAttM3", "PsCmpM3", "PsAttD3", "PsAttA2", "PsCmpA2", "PsInCmpA2", "PsAttD2", "PsCmpD2", "PsInCompD2", "PsAttFor", "PsCmpFor", "PsAttSq", "PsCmpSq", "PsAttBack", "PsCmpBack", "Shot", "Crosses", "CrossCmp", "KeyPass", "Chance", "Goal", "Ast", "TakeOn", "Success1v1", "DefAction", "DefActionA3", "DefActionM3", "DefActionD3", "DefActionA2", "DefActionD2", "Recovery", "RcvryA3", "RcvryM3", "RcvryD3", "Int", "IntA3", "IntM3", "IntD3", "TotalRecInt", "TotalDistancekm", "DistanceRunningBelowHighSpeedm", "DistanceRunningAtHighSpeedm", "DistanceSprintingm", "SprintsCount", "TotalHighIntensityRunsCount", "TotalDistanceAtHighIntensitym", "TopSustainedSpeedms"];
opts.VariableTypes = ["categorical", "categorical", "double", "double", "double", "double", "categorical", "categorical", "categorical", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double", "double"];

% Specify variable properties
opts = setvaropts(opts, ["player", "team", "AgeGroup", "Position", "PosCat"], "EmptyFieldRule", "auto");

% Import the data
BlindDataForDistributionNoGKs = readtable(workbookFile, opts, "UseExcel", false);

for idx = 2:size(dataLines, 1)
    opts.DataRange = "A" + dataLines(idx, 1) + ":BQ" + dataLines(idx, 2);
    tb = readtable(workbookFile, opts, "UseExcel", false);
    BlindDataForDistributionNoGKs = [BlindDataForDistributionNoGKs; tb]; %#ok<AGROW>
end

end